language: python
python:
        - "2.7"
        - "3.3"
        - "3.4"
        - "nightly"
        - "pypy"
install:
        - pip install pytest sphinx
        - pip install -e .
script:
        - python setup.py check --strict
        - sphinx-build -W -b html docs docs/_build/html
        - py.test -vvv
